// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AuditLogHandle : RemoteTableHandle<EventContext, AuditLog>
        {
            protected override string RemoteTableName => "AuditLog";

            public sealed class FieldUniqueIndex : UniqueIndexBase<long>
            {
                protected override long GetKey(AuditLog row) => row.Field;

                public FieldUniqueIndex(AuditLogHandle table) : base(table) { }
            }

            public readonly FieldUniqueIndex Field;

            internal AuditLogHandle(DbConnection conn) : base(conn)
            {
                Field = new(this);
            }

            protected override object GetPrimaryKey(AuditLog row) => row.Field;
        }

        public readonly AuditLogHandle AuditLog;
    }
}
