// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BenefitLocationHandle : RemoteTableHandle<EventContext, BenefitLocation>
        {
            protected override string RemoteTableName => "BenefitLocation";

            public sealed class LocationIdUniqueIndex : UniqueIndexBase<long>
            {
                protected override long GetKey(BenefitLocation row) => row.LocationId;

                public LocationIdUniqueIndex(BenefitLocationHandle table) : base(table) { }
            }

            public readonly LocationIdUniqueIndex LocationId;

            internal BenefitLocationHandle(DbConnection conn) : base(conn)
            {
                LocationId = new(this);
            }

            protected override object GetPrimaryKey(BenefitLocation row) => row.LocationId;
        }

        public readonly BenefitLocationHandle BenefitLocation;
    }
}
