// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BenefitLocationMapHandle : RemoteTableHandle<EventContext, BenefitLocationMap>
        {
            protected override string RemoteTableName => "BenefitLocationMap";

            public sealed class MapIdUniqueIndex : UniqueIndexBase<long>
            {
                protected override long GetKey(BenefitLocationMap row) => row.MapId;

                public MapIdUniqueIndex(BenefitLocationMapHandle table) : base(table) { }
            }

            public readonly MapIdUniqueIndex MapId;

            internal BenefitLocationMapHandle(DbConnection conn) : base(conn)
            {
                MapId = new(this);
            }

            protected override object GetPrimaryKey(BenefitLocationMap row) => row.MapId;
        }

        public readonly BenefitLocationMapHandle BenefitLocationMap;
    }
}
