// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PendingRegistrationHandle : RemoteTableHandle<EventContext, PendingRegistration>
        {
            protected override string RemoteTableName => "PendingRegistration";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PendingRegistration row) => row.Identity;

                public IdentityUniqueIndex(PendingRegistrationHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal PendingRegistrationHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(PendingRegistration row) => row.Identity;
        }

        public readonly PendingRegistrationHandle PendingRegistration;
    }
}
