// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AuditLog
    {
        [DataMember(Name = "Field")]
        public long Field;
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Action")]
        public string? Action;
        [DataMember(Name = "Details")]
        public string? Details;
        [DataMember(Name = "Timestamp")]
        public SpacetimeDB.Timestamp Timestamp;

        public AuditLog(
            long Field,
            SpacetimeDB.Identity Identity,
            string? Action,
            string? Details,
            SpacetimeDB.Timestamp Timestamp
        )
        {
            this.Field = Field;
            this.Identity = Identity;
            this.Action = Action;
            this.Details = Details;
            this.Timestamp = Timestamp;
        }

        public AuditLog()
        {
        }
    }
}
