// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AuthSession
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "LastActiveTime")]
        public SpacetimeDB.Timestamp LastActiveTime;
        [DataMember(Name = "ActiveDeviceId")]
        public string? ActiveDeviceId;

        public AuthSession(
            SpacetimeDB.Identity Identity,
            SpacetimeDB.Timestamp LastActiveTime,
            string? ActiveDeviceId
        )
        {
            this.Identity = Identity;
            this.LastActiveTime = LastActiveTime;
            this.ActiveDeviceId = ActiveDeviceId;
        }

        public AuthSession()
        {
        }
    }
}
