// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BenefitDefinition
    {
        [DataMember(Name = "BenefitId")]
        public long BenefitId;
        [DataMember(Name = "Name")]
        public string? Name;
        [DataMember(Name = "Description")]
        public string? Description;
        [DataMember(Name = "Provider")]
        public string? Provider;
        [DataMember(Name = "PolicyDetails")]
        public string? PolicyDetails;
        [DataMember(Name = "IsActive")]
        public bool IsActive;
        [DataMember(Name = "LocationId")]
        public long LocationId;
        [DataMember(Name = "CreatedAt")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "UpdatedAt")]
        public SpacetimeDB.Timestamp? UpdatedAt;

        public BenefitDefinition(
            long BenefitId,
            string? Name,
            string? Description,
            string? Provider,
            string? PolicyDetails,
            bool IsActive,
            long LocationId,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? UpdatedAt
        )
        {
            this.BenefitId = BenefitId;
            this.Name = Name;
            this.Description = Description;
            this.Provider = Provider;
            this.PolicyDetails = PolicyDetails;
            this.IsActive = IsActive;
            this.LocationId = LocationId;
            this.CreatedAt = CreatedAt;
            this.UpdatedAt = UpdatedAt;
        }

        public BenefitDefinition()
        {
        }
    }
}
