// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PendingVerification
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Username")]
        public string? Username;
        [DataMember(Name = "Email")]
        public string? Email;
        [DataMember(Name = "VerificationCode")]
        public string? VerificationCode;
        [DataMember(Name = "ExpiresAt")]
        public SpacetimeDB.Timestamp ExpiresAt;

        public PendingVerification(
            SpacetimeDB.Identity Identity,
            string? Username,
            string? Email,
            string? VerificationCode,
            SpacetimeDB.Timestamp ExpiresAt
        )
        {
            this.Identity = Identity;
            this.Username = Username;
            this.Email = Email;
            this.VerificationCode = VerificationCode;
            this.ExpiresAt = ExpiresAt;
        }

        public PendingVerification()
        {
        }
    }
}
