// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteBenefitDefinitionHandler(ReducerEventContext ctx, long benefitId);
        public event DeleteBenefitDefinitionHandler? OnDeleteBenefitDefinition;

        public void DeleteBenefitDefinition(long benefitId)
        {
            conn.InternalCallReducer(new Reducer.DeleteBenefitDefinition(benefitId), this.SetCallReducerFlags.DeleteBenefitDefinitionFlags);
        }

        public bool InvokeDeleteBenefitDefinition(ReducerEventContext ctx, Reducer.DeleteBenefitDefinition args)
        {
            if (OnDeleteBenefitDefinition == null) return false;
            OnDeleteBenefitDefinition(
                ctx,
                args.BenefitId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteBenefitDefinition : Reducer, IReducerArgs
        {
            [DataMember(Name = "benefitId")]
            public long BenefitId;

            public DeleteBenefitDefinition(long BenefitId)
            {
                this.BenefitId = BenefitId;
            }

            public DeleteBenefitDefinition()
            {
            }

            string IReducerArgs.ReducerName => "DeleteBenefitDefinition";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteBenefitDefinitionFlags;
        public void DeleteBenefitDefinition(CallReducerFlags flags) => DeleteBenefitDefinitionFlags = flags;
    }
}
