// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteBenefitLocationHandler(ReducerEventContext ctx, long locationId);
        public event DeleteBenefitLocationHandler? OnDeleteBenefitLocation;

        public void DeleteBenefitLocation(long locationId)
        {
            conn.InternalCallReducer(new Reducer.DeleteBenefitLocation(locationId), this.SetCallReducerFlags.DeleteBenefitLocationFlags);
        }

        public bool InvokeDeleteBenefitLocation(ReducerEventContext ctx, Reducer.DeleteBenefitLocation args)
        {
            if (OnDeleteBenefitLocation == null) return false;
            OnDeleteBenefitLocation(
                ctx,
                args.LocationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteBenefitLocation : Reducer, IReducerArgs
        {
            [DataMember(Name = "locationId")]
            public long LocationId;

            public DeleteBenefitLocation(long LocationId)
            {
                this.LocationId = LocationId;
            }

            public DeleteBenefitLocation()
            {
            }

            string IReducerArgs.ReducerName => "DeleteBenefitLocation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeleteBenefitLocationFlags;
        public void DeleteBenefitLocation(CallReducerFlags flags) => DeleteBenefitLocationFlags = flags;
    }
}
