// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GetBenefitsByLocationHandler(ReducerEventContext ctx, double latitude, double longitude, double radiusKm);
        public event GetBenefitsByLocationHandler? OnGetBenefitsByLocation;

        public void GetBenefitsByLocation(double latitude, double longitude, double radiusKm)
        {
            conn.InternalCallReducer(new Reducer.GetBenefitsByLocation(latitude, longitude, radiusKm), this.SetCallReducerFlags.GetBenefitsByLocationFlags);
        }

        public bool InvokeGetBenefitsByLocation(ReducerEventContext ctx, Reducer.GetBenefitsByLocation args)
        {
            if (OnGetBenefitsByLocation == null) return false;
            OnGetBenefitsByLocation(
                ctx,
                args.Latitude,
                args.Longitude,
                args.RadiusKm
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GetBenefitsByLocation : Reducer, IReducerArgs
        {
            [DataMember(Name = "latitude")]
            public double Latitude;
            [DataMember(Name = "longitude")]
            public double Longitude;
            [DataMember(Name = "radiusKm")]
            public double RadiusKm;

            public GetBenefitsByLocation(
                double Latitude,
                double Longitude,
                double RadiusKm
            )
            {
                this.Latitude = Latitude;
                this.Longitude = Longitude;
                this.RadiusKm = RadiusKm;
            }

            public GetBenefitsByLocation()
            {
            }

            string IReducerArgs.ReducerName => "GetBenefitsByLocation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags GetBenefitsByLocationFlags;
        public void GetBenefitsByLocation(CallReducerFlags flags) => GetBenefitsByLocationFlags = flags;
    }
}
