// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GetMyProfileHandler(ReducerEventContext ctx);
        public event GetMyProfileHandler? OnGetMyProfile;

        public void GetMyProfile()
        {
            conn.InternalCallReducer(new Reducer.GetMyProfile(), this.SetCallReducerFlags.GetMyProfileFlags);
        }

        public bool InvokeGetMyProfile(ReducerEventContext ctx, Reducer.GetMyProfile args)
        {
            if (OnGetMyProfile == null) return false;
            OnGetMyProfile(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GetMyProfile : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "GetMyProfile";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags GetMyProfileFlags;
        public void GetMyProfile(CallReducerFlags flags) => GetMyProfileFlags = flags;
    }
}
