// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MapBenefitToLocationHandler(ReducerEventContext ctx, long benefitId, long locationId);
        public event MapBenefitToLocationHandler? OnMapBenefitToLocation;

        public void MapBenefitToLocation(long benefitId, long locationId)
        {
            conn.InternalCallReducer(new Reducer.MapBenefitToLocation(benefitId, locationId), this.SetCallReducerFlags.MapBenefitToLocationFlags);
        }

        public bool InvokeMapBenefitToLocation(ReducerEventContext ctx, Reducer.MapBenefitToLocation args)
        {
            if (OnMapBenefitToLocation == null) return false;
            OnMapBenefitToLocation(
                ctx,
                args.BenefitId,
                args.LocationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MapBenefitToLocation : Reducer, IReducerArgs
        {
            [DataMember(Name = "benefitId")]
            public long BenefitId;
            [DataMember(Name = "locationId")]
            public long LocationId;

            public MapBenefitToLocation(
                long BenefitId,
                long LocationId
            )
            {
                this.BenefitId = BenefitId;
                this.LocationId = LocationId;
            }

            public MapBenefitToLocation()
            {
            }

            string IReducerArgs.ReducerName => "MapBenefitToLocation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MapBenefitToLocationFlags;
        public void MapBenefitToLocation(CallReducerFlags flags) => MapBenefitToLocationFlags = flags;
    }
}
