// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void QueryActiveBenefitsAtLocationHandler(ReducerEventContext ctx, long locationId);
        public event QueryActiveBenefitsAtLocationHandler? OnQueryActiveBenefitsAtLocation;

        public void QueryActiveBenefitsAtLocation(long locationId)
        {
            conn.InternalCallReducer(new Reducer.QueryActiveBenefitsAtLocation(locationId), this.SetCallReducerFlags.QueryActiveBenefitsAtLocationFlags);
        }

        public bool InvokeQueryActiveBenefitsAtLocation(ReducerEventContext ctx, Reducer.QueryActiveBenefitsAtLocation args)
        {
            if (OnQueryActiveBenefitsAtLocation == null) return false;
            OnQueryActiveBenefitsAtLocation(
                ctx,
                args.LocationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class QueryActiveBenefitsAtLocation : Reducer, IReducerArgs
        {
            [DataMember(Name = "locationId")]
            public long LocationId;

            public QueryActiveBenefitsAtLocation(long LocationId)
            {
                this.LocationId = LocationId;
            }

            public QueryActiveBenefitsAtLocation()
            {
            }

            string IReducerArgs.ReducerName => "QueryActiveBenefitsAtLocation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags QueryActiveBenefitsAtLocationFlags;
        public void QueryActiveBenefitsAtLocation(CallReducerFlags flags) => QueryActiveBenefitsAtLocationFlags = flags;
    }
}
