// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void QueryActiveBenefitsByTypeHandler(ReducerEventContext ctx, int typeInt);
        public event QueryActiveBenefitsByTypeHandler? OnQueryActiveBenefitsByType;

        public void QueryActiveBenefitsByType(int typeInt)
        {
            conn.InternalCallReducer(new Reducer.QueryActiveBenefitsByType(typeInt), this.SetCallReducerFlags.QueryActiveBenefitsByTypeFlags);
        }

        public bool InvokeQueryActiveBenefitsByType(ReducerEventContext ctx, Reducer.QueryActiveBenefitsByType args)
        {
            if (OnQueryActiveBenefitsByType == null) return false;
            OnQueryActiveBenefitsByType(
                ctx,
                args.TypeInt
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class QueryActiveBenefitsByType : Reducer, IReducerArgs
        {
            [DataMember(Name = "typeInt")]
            public int TypeInt;

            public QueryActiveBenefitsByType(int TypeInt)
            {
                this.TypeInt = TypeInt;
            }

            public QueryActiveBenefitsByType()
            {
            }

            string IReducerArgs.ReducerName => "QueryActiveBenefitsByType";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags QueryActiveBenefitsByTypeFlags;
        public void QueryActiveBenefitsByType(CallReducerFlags flags) => QueryActiveBenefitsByTypeFlags = flags;
    }
}
