// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RegisterUserHandler(ReducerEventContext ctx, string username, string email, int roleInt);
        public event RegisterUserHandler? OnRegisterUser;

        public void RegisterUser(string username, string email, int roleInt)
        {
            conn.InternalCallReducer(new Reducer.RegisterUser(username, email, roleInt), this.SetCallReducerFlags.RegisterUserFlags);
        }

        public bool InvokeRegisterUser(ReducerEventContext ctx, Reducer.RegisterUser args)
        {
            if (OnRegisterUser == null) return false;
            OnRegisterUser(
                ctx,
                args.Username,
                args.Email,
                args.RoleInt
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RegisterUser : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "email")]
            public string Email;
            [DataMember(Name = "roleInt")]
            public int RoleInt;

            public RegisterUser(
                string Username,
                string Email,
                int RoleInt
            )
            {
                this.Username = Username;
                this.Email = Email;
                this.RoleInt = RoleInt;
            }

            public RegisterUser()
            {
                this.Username = "";
                this.Email = "";
            }

            string IReducerArgs.ReducerName => "RegisterUser";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RegisterUserFlags;
        public void RegisterUser(CallReducerFlags flags) => RegisterUserFlags = flags;
    }
}
