// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RequestLoginCodeHandler(ReducerEventContext ctx, string email);
        public event RequestLoginCodeHandler? OnRequestLoginCode;

        public void RequestLoginCode(string email)
        {
            conn.InternalCallReducer(new Reducer.RequestLoginCode(email), this.SetCallReducerFlags.RequestLoginCodeFlags);
        }

        public bool InvokeRequestLoginCode(ReducerEventContext ctx, Reducer.RequestLoginCode args)
        {
            if (OnRequestLoginCode == null) return false;
            OnRequestLoginCode(
                ctx,
                args.Email
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RequestLoginCode : Reducer, IReducerArgs
        {
            [DataMember(Name = "email")]
            public string Email;

            public RequestLoginCode(string Email)
            {
                this.Email = Email;
            }

            public RequestLoginCode()
            {
                this.Email = "";
            }

            string IReducerArgs.ReducerName => "RequestLoginCode";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RequestLoginCodeFlags;
        public void RequestLoginCode(CallReducerFlags flags) => RequestLoginCodeFlags = flags;
    }
}
