// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UnmapBenefitFromLocationHandler(ReducerEventContext ctx, long benefitId, long locationId);
        public event UnmapBenefitFromLocationHandler? OnUnmapBenefitFromLocation;

        public void UnmapBenefitFromLocation(long benefitId, long locationId)
        {
            conn.InternalCallReducer(new Reducer.UnmapBenefitFromLocation(benefitId, locationId), this.SetCallReducerFlags.UnmapBenefitFromLocationFlags);
        }

        public bool InvokeUnmapBenefitFromLocation(ReducerEventContext ctx, Reducer.UnmapBenefitFromLocation args)
        {
            if (OnUnmapBenefitFromLocation == null) return false;
            OnUnmapBenefitFromLocation(
                ctx,
                args.BenefitId,
                args.LocationId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UnmapBenefitFromLocation : Reducer, IReducerArgs
        {
            [DataMember(Name = "benefitId")]
            public long BenefitId;
            [DataMember(Name = "locationId")]
            public long LocationId;

            public UnmapBenefitFromLocation(
                long BenefitId,
                long LocationId
            )
            {
                this.BenefitId = BenefitId;
                this.LocationId = LocationId;
            }

            public UnmapBenefitFromLocation()
            {
            }

            string IReducerArgs.ReducerName => "UnmapBenefitFromLocation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UnmapBenefitFromLocationFlags;
        public void UnmapBenefitFromLocation(CallReducerFlags flags) => UnmapBenefitFromLocationFlags = flags;
    }
}
