// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateProfileHandler(ReducerEventContext ctx, string email);
        public event UpdateProfileHandler? OnUpdateProfile;

        public void UpdateProfile(string email)
        {
            conn.InternalCallReducer(new Reducer.UpdateProfile(email), this.SetCallReducerFlags.UpdateProfileFlags);
        }

        public bool InvokeUpdateProfile(ReducerEventContext ctx, Reducer.UpdateProfile args)
        {
            if (OnUpdateProfile == null) return false;
            OnUpdateProfile(
                ctx,
                args.Email
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateProfile : Reducer, IReducerArgs
        {
            [DataMember(Name = "email")]
            public string Email;

            public UpdateProfile(string Email)
            {
                this.Email = Email;
            }

            public UpdateProfile()
            {
                this.Email = "";
            }

            string IReducerArgs.ReducerName => "UpdateProfile";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateProfileFlags;
        public void UpdateProfile(CallReducerFlags flags) => UpdateProfileFlags = flags;
    }
}
