// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void VerifyAccountHandler(ReducerEventContext ctx, string verificationCode);
        public event VerifyAccountHandler? OnVerifyAccount;

        public void VerifyAccount(string verificationCode)
        {
            conn.InternalCallReducer(new Reducer.VerifyAccount(verificationCode), this.SetCallReducerFlags.VerifyAccountFlags);
        }

        public bool InvokeVerifyAccount(ReducerEventContext ctx, Reducer.VerifyAccount args)
        {
            if (OnVerifyAccount == null) return false;
            OnVerifyAccount(
                ctx,
                args.VerificationCode
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class VerifyAccount : Reducer, IReducerArgs
        {
            [DataMember(Name = "verificationCode")]
            public string VerificationCode;

            public VerifyAccount(string VerificationCode)
            {
                this.VerificationCode = VerificationCode;
            }

            public VerifyAccount()
            {
                this.VerificationCode = "";
            }

            string IReducerArgs.ReducerName => "VerifyAccount";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags VerifyAccountFlags;
        public void VerifyAccount(CallReducerFlags flags) => VerifyAccountFlags = flags;
    }
}
