// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void VerifyEmailHandler(ReducerEventContext ctx, string verificationCode);
        public event VerifyEmailHandler? OnVerifyEmail;

        public void VerifyEmail(string verificationCode)
        {
            conn.InternalCallReducer(new Reducer.VerifyEmail(verificationCode), this.SetCallReducerFlags.VerifyEmailFlags);
        }

        public bool InvokeVerifyEmail(ReducerEventContext ctx, Reducer.VerifyEmail args)
        {
            if (OnVerifyEmail == null) return false;
            OnVerifyEmail(
                ctx,
                args.VerificationCode
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class VerifyEmail : Reducer, IReducerArgs
        {
            [DataMember(Name = "verificationCode")]
            public string VerificationCode;

            public VerifyEmail(string VerificationCode)
            {
                this.VerificationCode = VerificationCode;
            }

            public VerifyEmail()
            {
                this.VerificationCode = "";
            }

            string IReducerArgs.ReducerName => "VerifyEmail";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags VerifyEmailFlags;
        public void VerifyEmail(CallReducerFlags flags) => VerifyEmailFlags = flags;
    }
}
